name: district_online_service
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  #  Firebase .....
  firebase_core: ^3.3.0
  #  cloud firestore
  cloud_firestore: ^5.2.1
  #  Firebase Storage
  firebase_storage: ^12.1.3
#  Firebase Authentication
  firebase_auth: ^5.2.0
# For Cupertino Icons
  cupertino_icons: ^1.0.8
# Flutter Svg Image
  flutter_svg: ^2.0.10+1
#  For url handel
  url_launcher: ^6.2.6
  #  Image Get
  image_picker: ^1.1.2
  icons_plus: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/e-seba-icon/
    - assets/pdf/
    - assets/icons/
    - assets/logos/
    - assets/svg_image/
  fonts:
    - family: kalpurush
      fonts:
        - asset: fonts/kalpurush.ttf
        - asset: fonts/Poppins-Regular.ttf
